### ISSUE TITLE
[Linux] App Crash when Start Playing

### ISSUE THREAD

**Issue by smolleyes** [jaruba/wcjs-player#2] opened 2015-06-18 23:04 UTC
hello jaruba :)

ok just trying your new project on my old laptop

the pluginbuild and load fineinmy realllyyy basic nw app

when i start it, it s buffeering then just crash no vlc infos or anything in the terminal... an idear on how to debug this?

thanks

**Comment by jaruba** [comment] 2015-06-18 23:25
What OS?

**Comment by smolleyes** [comment] 2015-06-18 23:26
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04.1
Codename:	trusty

**Comment by smolleyes** [comment] 2015-06-18 23:27
nw12

**Comment by jaruba** [comment] 2015-06-18 23:50
Uhm.. If it's buffering correctly and works with a basic app, then it means that vlc and the ``webchimera.js`` modules have been added correctly to the app.

If it breaks right after buffering then there must be a problem with drawing to the canvas, it is most probably an issue in [webchimera.js](https://github.com/RSATom/WebChimera.js) or something that  breaks in [wcjs-renderer](https://github.com/RSATom/wcjs-renderer)'s functions (either ``frameSetup()`` or ``render()``)

I've not seen JavaScript freeze NW.js or the Browser yet (not unless it gets stuck in an infinite loop or waits for a synchroneous response). I'm pretty sure that ``wcjs-player`` can't be the reason for this..

For debugging, @RSATom or @Ivshti should be able to help more, as I did not work on the C++ side of ``webchimera.js`` at all. It might just be a bug in your app though..

I know @Ivshti is already using it in [Stremio](http://www.strem.io/) and has not reported any such behavior.

In the meanwhile (as they should be online only after at least 4-5 hours from now), you can try some of the following tests:

- check if NW.js v12 [supports WebGL](http://stackoverflow.com/questions/11871077/proper-way-to-detect-webgl-support#answer-11871182) on Linux

- reinstall graphic drivers

- try using ``wcjs-renderer`` ([demo usage](https://github.com/RSATom/wcjs-ugly-demo)) directly in the same scenario and see if it still crashes (this will tell us if something that ``wcjs-player`` does might be the problem)

Also, did you by any chance attach any event listeners to the ``webchimera.js`` object? (ie: ``wjs().vlc`` object)

**Comment by smolleyes** [comment] 2015-06-19 00:06
will try the wcjs-renderer 

i m on a old laptop with basic radeon drivers maybe this is the issue

brb

**Comment by smolleyes** [comment] 2015-06-19 00:10
wcjs-ugly-demo crash directly too just seevthe nw window then crash

**Comment by jaruba** [comment] 2015-06-19 00:13
Then it's something with the graphic's card (or the drivers), ``webchimera.js`` module or VLC itself that's creating the problem..

**Comment by smolleyes** [comment] 2015-06-19 00:14
don t seem to have problem with hw accel

http://paste.ubuntu.com/11738019/

from chrome://gpu in my test nw app

**Comment by smolleyes** [comment] 2015-06-19 00:16
http://webglsamples.org/aquarium/aquarium.html works and do not crash my app too (very very slow 6 fps/sec with 50 fish ...) but no crash

**Comment by smolleyes** [comment] 2015-06-19 00:17
i ll install fglrx.. brb

**Comment by jaruba** [comment] 2015-06-19 00:23
> http://webglsamples.org/aquarium/aquarium.html works and do not crash my app too (very very slow 6 fps/sec with 50 fish ...) but no crash

Awesome sample! I'm having so much fun with it right now. :))

> don t seem to have problem with hw accel

We've have some issues with WebChimera and a graphics card (only one specific card was reported by 2 users: https://github.com/RSATom/WebChimera/issues/64#issuecomment-71331977 ) in the past with the Plugin.

**Comment by jaruba** [comment] 2015-06-19 00:35
> very very slow 6 fps/sec with 50 fish

Your FPS is incredibly low for only 50 fish.. Maybe the graphic's card simply can't handle the weight of playback. Have you tried running the same video in VLC directly? From our tests ``webchimera.js`` only uses a tiny bit more resources then VLC.

**Comment by Ivshti** [comment] 2015-06-19 06:04
If you don't have a GPU problem, then I know this behavior - VLC cannot find its plugins and stars rendering with some stupid fallback that is slow and crashes the app. Check for VLC error messages in the command prompt

**Comment by Ivshti** [comment] 2015-06-19 06:08
We should disable this, whatever it is, because users might think webchimera.js is at fault.

@RSATom any idea what might it be? I've seen it on OS X

**Comment by RSATom** [comment] 2015-06-19 06:13
@Ivshti, don't know. For me it works on linux. Tried right now.

**Comment by RSATom** [comment] 2015-06-19 06:16
@smolleyes, what exactly did you try run? And where did you get it, from npm or github repo?

**Comment by smolleyes** [comment] 2015-06-19 13:23
hello

just installed wcjs-player from npm...

created a basic package.json
installed nw12 files

created a html with a #player div in the body and the exemple js file on the readme....

i can read any file with vlc on this old pc even hevc with few lags sometimes but 3d is very slow yes but it don t explain why the app totally crash it s not just slow as the aquarium test...

i don t have any infos in the terminal from vlc ivshti

when i startthe app i have 

```
./nw .
[5640:0619/152204:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[5660:0619/152205:ERROR:sandbox_linux.cc(325)] InitializeSandbox() called with multiple threads in process gpu-process

```

(have the same errors in my streamstudio app and nothing crash when playing videos thru videoelement.js)

maybe he doesn t like my vlc 2.2.1 from ppa?

thx :)

**Comment by smolleyes** [comment] 2015-06-19 13:26
i ll try the nw 0.12.1

it fix the crashdump not available in 0.12 then maybe rogerwang or someone else can get more infos with it (don t know how to read this dump...)

**Comment by smolleyes** [comment] 2015-06-19 13:38
ok here s the dump file

same crash with nw 12.1

https://www.streamstudio.me/StreamStudio/nw12/dump.zip

++

**Comment by RSATom** [comment] 2015-06-19 14:01
@smolleyes, could you please try run this: https://github.com/RSATom/wcjs-ugly-demo ?

**Comment by smolleyes** [comment] 2015-06-19 14:31
tried yesterday

same problem direct crash:p

**Comment by RSATom** [comment] 2015-06-19 14:42
ok, will try myself on xubuntu...

**Comment by RSATom** [comment] 2015-06-19 17:41
tried on xubuntu 14 - didn't get any crash

**Comment by RSATom** [comment] 2015-06-19 17:43
@smolleyes, could you please try with electron? I've updated repo with instructions and required scripts: https://github.com/RSATom/wcjs-ugly-demo

**Comment by smolleyes** [comment] 2015-06-20 16:32
hello

just tried on my normal pc

for electron

Renderer process started
[24894:0620/181903:INFO:CONSOLE(83)] "Uncaught Error: Module version mismatch. Expected 44, got 43.", source: /tmp/wcjs-ugly-demo/node_modules/wcjs-renderer/node_modules/webchimera.js/node_modules/bindings/bindings.js (83)

won t start or crash

for nwjs12.2

/tmp/wcjs-ugly-demo/nw: symbol lookup error: /tmp/wcjs-ugly-demo/node_modules/wcjs-renderer/node_modules/webchimera.js/build/Release/WebChimera.js.node: undefined symbol: libvlc_new

... :p

**Comment by RSATom** [comment] 2015-06-20 16:35
for error with Electron: update Electron binaries to the latest version.
for error with nw.js: add libvlc to your PATH environment variable

**Comment by smolleyes** [comment] 2015-06-20 16:57
just updated vlc and libvlc-dev from ppa to 2.2.1 then reinstalled wcjs-player

it install and build fine but still

/tmp/test/nw: symbol lookup error: /tmp/test/node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/build/Release/WebChimera.js.node: undefined symbol: libvlc_new

don t understand

**Comment by RSATom** [comment] 2015-06-20 16:59
I think it just can't find libvlc from your ppa installation.

**Comment by RSATom** [comment] 2015-06-20 17:00
try install vlc not from ppa, and if it will work - we will try find the way to solve problem with libvlc from ppa

**Comment by RSATom** [comment] 2015-06-20 17:01
tbh, I didn't try use vlc from ppa

**Comment by smolleyes** [comment] 2015-06-20 17:02
without ppa vlc on ubuntu is a shame... too old

i ll try

i added th same ppa yesterday on my old laptop without this error... strange

**Comment by smolleyes** [comment] 2015-06-20 17:08
damn!

removed all my ppa, vlc libvlc-dev....

reinstalled in 2.1.6 form ubuntu repo and same error

/tmp/test/nw: symbol lookup error: /tmp/test/node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/build/Release/WebChimera.js.node: undefined symbol: libvlc_new

:/

**Comment by RSATom** [comment] 2015-06-20 17:10
what exactly vlc packages did you install?

**Comment by smolleyes** [comment] 2015-06-20 17:13
vlc (2.1.6-0ubuntu14.04.1) 

 http://fr.archive.ubuntu.com/ubuntu/ trusty-updates/universe libvlc-dev amd64 2.1.6-0ubuntu14.04.1 [25,4 kB]

**Comment by RSATom** [comment] 2015-06-20 17:14
`sudo apt-get install vlc vlc-dev` - right?

**Comment by smolleyes** [comment] 2015-06-20 17:15
sudo apt-get install vlc  libvlc-dev yes

**Comment by smolleyes** [comment] 2015-06-20 17:17
dpkg -l | grep libvlc

give me (seems right)

ii  libvlc-dev                                            2.1.6-0ubuntu14.04.1                                amd64        development files for libvlc
ii  libvlc5                                               2.1.6-0ubuntu14.04.1                                amd64        multimedia player and streamer library
ii  libvlccore7                                           2.1.6-0ubuntu14.04.1                                amd64        base library for VLC and its modules

**Comment by smolleyes** [comment] 2015-06-20 17:18
don t know if i must have a libvlc_new.so somewhere but can t find it...

**Comment by RSATom** [comment] 2015-06-20 17:18
it seems I just forget link vlc on linux: https://github.com/RSATom/ya-libvlc-wrapper/blob/master/CMakeLists.txt

**Comment by RSATom** [comment] 2015-06-20 17:19
but don't understand why it worked for me...

**Comment by smolleyes** [comment] 2015-06-20 17:19
:) don t know

i ll wait for your fix

**Comment by RSATom** [comment] 2015-06-20 17:24
you could try add 
`target_link_libraries( ${PROJECT_NAME} vlc )` to https://github.com/RSATom/WebChimera.js/blob/master/CMakeLists.txt#L30

**Comment by smolleyes** [comment] 2015-06-20 17:37
ok

add it then node rebuild.js

it load and no crash but won t play file

Fontconfig warning: FcPattern object size does not accept value "0"
Fontconfig warning: FcPattern object size does not accept value "0"
Fontconfig warning: FcPattern object size does not accept value "0"
Fontconfig warning: FcPattern object size does not accept value "0"
[0x3774efcdfe98] main vout display error: Failed to change zoom
[0x3774efcdfe98] main vout display error: Failed to set on top
[0x3774efcdfe98] main vout display error: Failed to change source AR

**Comment by RSATom** [comment] 2015-06-20 17:38
link used in `ugly` demo is little bit slow, try set your own link there.

**Comment by smolleyes** [comment] 2015-06-20 17:41
trying with http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4

same thing

**Comment by smolleyes** [comment] 2015-06-20 17:42
./nw .
[16441:0620/194224:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[16461:0620/194224:ERROR:sandbox_linux.cc(325)] InitializeSandbox() called with multiple threads in process gpu-process
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x30b7075a4800] max_analyze_duration reached
Fontconfig warning: FcPattern object size does not accept value "0"
Fontconfig warning: FcPattern object size does not accept value "0"
Fontconfig warning: FcPattern object size does not accept value "0"
Fontconfig warning: FcPattern object size does not accept value "0"
[0x30b7071e4898] main vout display error: Failed to change zoom
[0x30b7071e4898] main vout display error: Failed to set on top
[0x30b7071e4898] main vout display error: Failed to change source AR
[16441:0620/194227:ERROR:backend_impl.cc(1364)] Unable to map Index file

**Comment by RSATom** [comment] 2015-06-20 17:44
ok, I'll look again by myself tomorrow. It seems I missed something.

**Comment by smolleyes** [comment] 2015-06-20 17:47
more infos...

ATTENTION: default value of option force_s3tc_enable overridden by environment.
[17998:0620/194646:ERROR:sandbox_linux.cc(325)] InitializeSandbox() called with multiple threads in process gpu-process
[00001f23e771f098] core vout display error: Failed to change zoom
[00001f23e771f098] core vout display error: Failed to set on top
[00001f23e771f098] core vout display error: Failed to change source AR
[00001f23e792abf8] core input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 1041 ms)
[00001f23e792abf8] core input error: ES_OUT_RESET_PCR called
Non-reference picture received and no reference available
[h264 @ 0x1f23e75e7c00] decode_slice_header error

**Comment by RSATom** [comment] 2015-06-20 17:49
could you try some local file?

**Comment by smolleyes** [comment] 2015-06-20 17:50
ok brb

**Comment by smolleyes** [comment] 2015-06-20 17:51
R:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[18651:0620/195122:ERROR:sandbox_linux.cc(325)] InitializeSandbox() called with multiple threads in process gpu-process
[00002f6ae7d19698] core vout display error: Failed to change zoom
[00002f6ae7d19698] core vout display error: Failed to set on top
[00002f6ae7d19698] core vout display error: Failed to change source AR

same output

**Comment by RSATom** [comment] 2015-06-20 17:53
ok, thanks, will try the same tomorrow, since I don't have access to my linux box right now.

**Comment by RSATom** [comment] 2015-06-20 17:53
btw, what hardware do you have?

**Comment by smolleyes** [comment] 2015-06-20 17:54
lspci | grep VGA
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Turks XT [Radeon HD 6670/7670]

with radeon driver, core i5 ...

**Comment by RSATom** [comment] 2015-06-20 17:55
i.e. you have two video cards?

**Comment by smolleyes** [comment] 2015-06-20 18:02
no

**Comment by RSATom** [comment] 2015-06-20 18:03
hm... your I5 does not contain gpu?

**Comment by smolleyes** [comment] 2015-06-20 18:15
lshw -class display
ATTENTION: ce programme devrait être lancé en tant que super-utilisateur.
  *-display               
       description: VGA compatible controller
       produit: Turks XT [Radeon HD 6670/7670]
       fabriquant: Advanced Micro Devices, Inc. [AMD/ATI]
       identifiant matériel: 0
       information bus: pci@0000:01:00.0
       version: 00
       bits: 64 bits
       horloge: 33MHz
       fonctionnalités: vga_controller bus_master cap_list rom
       configuration: driver=radeon latency=0
       ressources: irq:35 mémoire:e0000000-efffffff mémoire:f7e20000-f7e3ffff portE/S:e000(taille=256) mémoire:f7e00000-f7e1ffff

don t think so

**Comment by RSATom** [comment] 2015-06-20 18:15
ok, thanks

**Comment by smolleyes** [comment] 2015-06-20 18:15
np :)

**Comment by RSATom** [comment] 2015-06-22 04:04
@smolleyes, tried again on all platforms I have - everywhere it works... Ok, let's try add some debug logging inside `wcjs-renderer`. Could you please add something like `console.log("...")` inside:
* [frameSetup](https://github.com/RSATom/wcjs-renderer/blob/master/index.js#L141)
* [render](https://github.com/RSATom/wcjs-renderer/blob/master/index.js#L26)

**Comment by jaruba** [comment] 2015-06-30 14:14
I've managed to reproduce this behavior.. Using mrl:

    http://trailers.divx.com/divx_prod/divx_plus_hd_showcase/Sintel_DivXPlus_6500kbps.mkv

Whenever I have my laptop unplugged from the power source it always freezes the app right before starting playback or after a few frames of very laggy playback.

It seems that when it happens when ``WebChimera.js`` reaches some sort of resource limit.. It's strange that all other software on the laptop works fine in this time..

**Comment by RSATom** [comment] 2015-06-30 15:15
Could you please add logging to `renderer`? We should know, if it called only few times.

**Comment by jaruba** [comment] 2015-06-30 15:17
I'll try.. but I don't think that's possible, most of the time the app freezes before the dev console is fully loaded.

**Comment by RSATom** [comment] 2015-06-30 15:19
understand, then what if remove content of `frameSetup` and `render` - will it freeze or not?

**Comment by jaruba** [comment] 2015-06-30 15:47
I managed to freeze it with ``console.log()``'s. The app freezes but JS keeps going, I see it takes a long time to process these lines:

https://github.com/RSATom/wcjs-renderer/blob/master/index.js#L29-L30

Line 30 usually takes a lot longer then line 29 though, but it does seem to continue even if the app froze. Plugging the laptop back makes the code run a lot faster but the app does not get restored.

**Comment by jaruba** [comment] 2015-06-30 15:51
Still.. for it to freeze I have to at least also have Powder open and playing a video + some software that uses a lot of resources..

**Comment by jaruba** [comment] 2015-06-30 15:56
Froze it again, same results.. those lines take a bit longer.. but this time something interesting happened, after a few minutes, the app started working again, framing a lot, but working none the less..

**Comment by RSATom** [comment] 2015-06-30 16:27
It seems problem is somewhere inside chromium. As I understand it correctly, on `videoFrame.y.fill` chromium have to copy memory buffer.

**Comment by RSATom** [comment] 2015-06-30 16:30
did you try use empty `render`?

**Comment by Ivshti** [comment] 2015-06-30 16:32
I am meeting an issue on some Windows cases where texImage2D ( videoFrame.x.fill ) takes up to 99% of the CPU of the program (analyzed with chromium debugger). The weird thing is, in that case, low quality videos behave normal - texImage2D takes up to 2%, while HD videos bump to 99%.

It could be some chromium issue.

**Comment by RSATom** [comment] 2015-07-02 16:06
I've fixed `frameReady` flood problem. Please test current version from npm.

**Comment by jaruba** [comment] 2015-07-02 16:46
Tested, it's the first time I've managed to see the entire full hd video to the end. I can confirm that it unfreezes A LOT faster.

I get freeze/unfreeze of the app every second for about 1 second.. sometimes it just prints one frame and freezes again.

Did you also add a flag like @Ivshti said?

**Comment by RSATom** [comment] 2015-07-02 16:50
so it's still noticeable freeze, ok, will try investigate it further...

> Did you also add a flag like @Ivshti said?

No, but in this case it will not help anyway.

**Comment by RSATom** [comment] 2015-07-02 16:57
@jaruba, could you please try comment content of `render` and look if still will freeze?

**Comment by jaruba** [comment] 2015-07-02 17:01
@RSATom tested, the app is very laggy with ``renderer`` commented out no noticeable freeze, but elements noticeably stay behind the mouse events that I trigger..

**Comment by RSATom** [comment] 2015-07-02 17:04
Maybe it's related to other libvlc events handlers? Do you do something heavy there?

**Comment by jaruba** [comment] 2015-07-02 17:06
nope... nothing heavy.. if I change to a low resolution video the entire UI works faster.

**Comment by RSATom** [comment] 2015-07-02 17:09
hm... sounds strange... What cpu load do you have on that?

**Comment by jaruba** [comment] 2015-07-02 17:10
I can't check atm, ran out of battery, can only test when I have the laptop unplugged :P

**Comment by jaruba** [comment] 2015-07-02 17:13
How would I check the CPU load of an App? With Task Manager?

**Comment by RSATom** [comment] 2015-07-02 17:13
yes

**Comment by RSATom** [comment] 2015-07-02 17:15
and it's not urgent - I will not do anything more today.

**Comment by jaruba** [comment] 2015-07-02 17:21
I did not comment out ``frameSetup`` yet though, could it be the cause for the lag?

**Comment by RSATom** [comment] 2015-07-02 17:25
it doesn't matter since it called only once

**Comment by jaruba** [comment] 2015-07-02 17:31
CPU - Utilization 33% (went to ~60% at one point for about 10-15 seconds)

**Comment by jaruba** [comment] 2015-07-02 17:31
but truth be told the entire OS is laggy, chrome too

**Comment by RSATom** [comment] 2015-07-02 17:32
how many cores your cpu have?

**Comment by jaruba** [comment] 2015-07-02 17:35
Intel i7-4500U - 2 Cores

**Comment by RSATom** [comment] 2015-07-02 17:37
hm... pretty powerful.

**Comment by jaruba** [comment] 2015-07-02 17:40
yeah.. but again.. this is with the laptop in some power saving mode, with powder player playing a video + a chrome window with 43 tabs open, and a lot of other software open, the entire OS is just a bit laggy

**Comment by jaruba** [comment] 2015-07-02 17:49
If I stop playback in Powder Player, things dramatically change for the better.. The Full HD video, although still framing badly, can at least be seen in most cases, extremely short freezes but they happen a lot, a 720p local video runs almost perfectly though..

**Comment by Ivshti** [comment] 2015-07-02 18:03
So there is no freeze now?

**Comment by Ivshti** [comment] 2015-07-02 18:04
@jaruba did you try vlc player with the same video? I'm guessing it would do fine. If so, then teximage2d struggles under slow hardware and we should do everything possible to find a better way

**Comment by jaruba** [comment] 2015-07-02 18:08
tested with VLC now, it does not surprise me that it works flawlessly, I have a powerful laptop that's unplugged, even in power saving mode, as you mentioned, players request more resources to handle their load.

**Comment by jaruba** [comment] 2015-07-02 18:15
> So there is no freeze now?

It does still freeze, just unfreezes very fast.. you could call it framing, but the entire app frames, not only the video.

**Comment by Ivshti** [comment] 2015-07-02 18:22
I see - and what's the CPU usage of WCjs vs VLC - can we rule this to some extend to app not having priority ?

**Comment by jaruba** [comment] 2015-07-02 18:27
> can we rule this to some extend to app not having priority

It would definitely work perfectly for me if the app had priority, it would work just as bad on a slow laptop/PC though.. although the entire UI is framing.. it is still possible to use it.. just have to be patient after every click.. :)

Personally, I can't imagine what could be done more for this.. it's just sad.. if only the video would have this problem it wouldn't bother me as much, but knowing that the UI behaves like this in some cases.. makes the entire app feel unprofessional.

**Comment by Ivshti** [comment] 2015-07-02 18:46
Just summarizing one more time to make sure I've understood - if the app had priority (simulated by the laptop being plugged in - it works perfectly?

Also, we should note that because of chromiums architecture, we always have (at least) one memcpy per frame, which means our overhead over VLC is growing exponentially with the frame size - as we have found out from tests. And it gets fatal at full HD / 1080p.

Something must be done about this, and theoretically I'm not sure if it's possible - the GPU memory should only be accessible by the GPU process, and we need access to it to init a PBO (@RSATom - say something if I'm wrong).

**Comment by jaruba** [comment] 2015-07-02 18:51
> Just summarizing one more time to make sure I've understood - if the app had priority (simulated by the laptop being plugged in - it works perfectly?
> Also, we should note that because of chromiums architecture, we always have (at least) one memcpy per frame, which means our overhead over VLC is growing exponentially with the frame size - as we have found out from tests. And it gets fatal at full HD / 1080p.

Correct. This last fix was a good find it works a lot better now, the app does not stay frozen at least.

**Comment by jaruba** [comment] 2015-07-02 19:00
@Ivshti Do you think it's worth testing the fallback renderer in this scenario too?

**Comment by Ivshti** [comment] 2015-07-02 19:00
Also, I bet the modern UNIXes do some magic to prioritize processes that need the CPU, and to give them what they need. Usually OS X and Linux schedulers are very smart.

**Comment by Ivshti** [comment] 2015-07-02 19:01
@jaruba  Re fallback renderer: yes, test it. I'm curious as to how it would perform, and through some weird circumstances it *might* work better (e.g. chrome detecting that it needs priority).

**Comment by jaruba** [comment] 2015-07-02 19:03
I'm also wondering what would happen if I start playback on a video element. :ghost:

**Comment by jaruba** [comment] 2015-07-02 19:08
wcjs-renderer\index.js:36
    Uncaught TypeError: Cannot read property 'data' of undefined

**Comment by Ivshti** [comment] 2015-07-02 19:35
@jaruba fixed, try again

**Comment by jaruba** [comment] 2015-07-02 20:06
@Ivshti It's not fixed.. the issue is here:

https://github.com/RSATom/wcjs-renderer/blob/master/index.js#L52-L57

The reason: http://stackoverflow.com/questions/6796194/canvas-getcontext2d-returns-null#answer-13406681

Short description: you can only use ``.getContext()`` once, second time it's used it will always return ``null``.

**Comment by jaruba** [comment] 2015-07-02 20:10
I just removed the ``.getContext("webgl")`` line entirely just to test the fallback renderer, it's worst. :))

It frames on 720p even when the laptop is plugged in but it acts the same, a lot of very short freezes, just more frequent freezes.

**Comment by jaruba** [comment] 2015-07-03 15:00
@smolleyes Could you please test it and see if it is playing for you on that laptop with the latest version of ``wcjs-player``? I'm expecting it to have terrible lag, but I'm also expecting it to play the video. :)

**Comment by smolleyes** [comment] 2015-07-03 19:58
Hello

Ok i ll retry asap :p

**Comment by smolleyes** [comment] 2015-07-03 20:49
jaruba

do i need to have nw installed globally ? before building

**Comment by smolleyes** [comment] 2015-07-03 21:13
don t know maybe i m stupid, it s crazy

[17540:0703/231248:ERROR:nw_shell.cc(335)] TypeError: Cannot read property 'addRule' of undefined
    at Object.<anonymous> (/home/yasmin/Documents/chimera/node_modules/wcjs-player/index.js:36:32)
    at Module._compile (module.js:451:26)
    at Object.Module._extensions..js (module.js:469:10)
    at Module.load (module.js:346:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:356:17)
    at require (module.js:375:17)
    at window.require (<anonymous>:4:17)
    at HTMLDocument.<anonymous> (file:///home/yasmin/Documents/chimera/js/main.js:4:12)
    at HTMLDocument.f.event.dispatch (file:///home/yasmin/Documents/chimera/js/jquery.min.js:3:4816)
[17540:0703/231248:INFO:CONSOLE(36)] "Uncaught TypeError: Cannot read property 'addRule' of undefined", source: /home/yasmin/Documents/chimera/node_modules/wcjs-player/index.js (36)

**Comment by smolleyes** [comment] 2015-07-03 21:13
if i pass it i have errors with buffers

**Comment by smolleyes** [comment] 2015-07-03 21:14
and with wcjs-ugly i just have a blank page....

**Comment by smolleyes** [comment] 2015-07-03 21:26
damn 

here s my html... simple

```
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>test</title>
</head>
<body>
	<div id="player"></div>	
	<script>
	var wjs = require("wcjs-player");
	var player = new wjs("#player").addPlayer({ autoplay: true });
	player.addPlaylist("http://archive.org/download/CartoonClassics/Krazy_Kat_-_Keeping_Up_With_Krazy.mp4");
	</script>
</body>
</html>

```

and i have the addRule error ...

**Comment by smolleyes** [comment] 2015-07-03 21:31
adding

<link rel="stylesheet" type="text/css" href="node_modules/wcjs-player/public/general.css">

to the index.html

and same direct crash than before...

**Comment by jaruba** [comment] 2015-07-03 21:40
> and same direct crash than before...

so it wasn't the cause for your bug... :(

> and i have the addRule error ...

The ``addRule`` lines: https://github.com/jaruba/wcjs-player/blob/master/index.js#L35-L38 add the scrollbar css to the page, they need to be injected in the page directly and not inside a css file because for some reason the scrollbar simply doesn't get styled if it's inside an injected CSS file.

I can't imagine why you wouldn't have the ``window.document`` object... are you using ``NW.js v0.12.2``?

**Comment by jaruba** [comment] 2015-07-03 21:49
Maybe the ``addRule`` error is only on the Linux version of ``NW.js`` for some insane reason..

**Comment by smolleyes** [comment] 2015-07-03 21:53
don t know... yes it s 0.12.2

will retry on my desktop pc tomorrow :)

**Comment by RSATom** [comment] 2015-07-07 08:57
it seems I found the bug: https://github.com/RSATom/wcjs-ugly-demo/issues/2

**Comment by RSATom** [comment] 2015-07-07 14:33
Published updated version to npm. I hope now crash is fixed.

**Comment by jaruba** [comment] 2015-07-07 16:00
@smolleyes 

When you check if the new version works now on linux, could you also try to change these lines from the player:

https://github.com/jaruba/wcjs-player/blob/master/index.js#L36-L38

and try ``global.window.document.`` or ``document.`` instead of ``window.document`` to see if it fixes the ``.addRule`` errors? Sorry for asking for this, but I don't have Linux installed to test on. :)

**Comment by jaruba** [comment] 2015-07-12 21:01
Closing due to inactivity, I'm going to presume this is fixed.

@smolleyes Please reopen the issue if you have time to test it and find that it still does not work.

**Comment by RSATom** [comment] 2015-11-18 04:17
@joacodeviaje, I think you've met the same libvlc bug as in https://github.com/jaruba/wcjs-player/issues/21

**Comment by joacodeviaje** [comment] 2015-11-18 17:18
I'm not compiling nor copying files. Just trying to run using nw.

**Comment by RSATom** [comment] 2015-11-18 17:30
But from where should load libvlc then? You need download this https://github.com/RSATom/WebChimera.js/releases/download/v.0.1.3/libvlc_2.2.1_mac.zip and extract it near the `WebChimera.js.node`

**Comment by WilliamAnthony** [comment] 2015-12-21 15:26
@jaruba, I'm on Linux and I got the error same as @smolleyes did. I've tried as your suggestion, `global.window.document.` and `global.window.document.` throws `TypeError: Cannot read property 'addRule' of undefined` error.
`document.` throws `ReferenceError: document is not defined`

I'm using:
nw v0.12.3
wcjs-player v0.5.2
webchimera.js v0.1.43

I've tried webgl-video-renderer v0.1.2 too, it's worked but I need multiplayer which is looks like unsupported using webgl-video-renderer.

**Comment by RSATom** [comment] 2015-12-21 15:47
@WilliamAnthony, what do you mean by "multiplayer"?

**Comment by WilliamAnthony** [comment] 2015-12-21 16:00
I mean multiscreen player in one window

**Comment by RSATom** [comment] 2015-12-21 16:06
ok, understand.

What exactly error did you get?

**Comment by WilliamAnthony** [comment] 2015-12-21 16:18
as I said at my previous comment, if I changed the code (line 41-45) to:
> * `global.window.document.` and `window.document.` throws `TypeError: Cannot read property 'addRule' of undefined` error.
> * `document.` throws `ReferenceError: document is not defined`

**Comment by RSATom** [comment] 2015-12-21 16:23
but why you changed it?

**Comment by RSATom** [comment] 2015-12-21 16:24
@jaruba's instructions was only for @smolleyes, and it's outdated comments.

**Comment by WilliamAnthony** [comment] 2015-12-21 16:27
because I have the same error like @smolleyes had

**Comment by RSATom** [comment] 2015-12-21 16:28
what exactly error it was?

**Comment by RSATom** [comment] 2015-12-21 16:29
@WilliamAnthony, did you try run https://github.com/jaruba/node-vlc-multiscreen ?

**Comment by WilliamAnthony** [comment] 2015-12-21 16:37
my error
> [8589:1221/232955:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'addRule' of undefined
>     at Object.<anonymous> (/home/william/workspace/nodejs/testplayer/node_modules/wcjs-player/index.js:41:35)
>     at Module._compile (module.js:451:26)
>     at Object.Module._extensions..js (module.js:469:10)
>     at Module.load (module.js:346:32)
>     at Function.Module._load (module.js:301:12)
>     at Module.require (module.js:356:17)
>     at require (module.js:375:17)
>     at window.require (<anonymous>:4:17)
>     at file:///home/william/workspace/nodejs/testplayer/show.html:9:11
> [8589:1221/232955:INFO:CONSOLE(41)] "Uncaught TypeError: Cannot read property 'addRule' of undefined", source: /home/william/workspace/nodejs/testplayer/node_modules/wcjs-player/index.js (41)

And no, I have not tried node-vlc-multiscreen

**Comment by WilliamAnthony** [comment] 2015-12-21 16:57
Ok, I know what causing the error now.
The HTML file should include at least empty <style></style> tag.
Omitting the <style> tag will throws the error.

**Comment by jaruba** [comment] 2016-01-19 06:51
I'm gonna close this again. :dancer:

**Closed by jaruba** 2016-01-19 06:51 UTC
Labels: bug
